config/routes.rb
Rails.application.routes.draw do
  root to: 'repositories#index'
  
  resources :repositories, only: %i[index show] do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
class Repository < ApplicationRecord
  validates_presence_of :github_id, :name, :url
  validates_uniqueness_of :github_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: :show
  before_action :set_languages

  def search
    @repositories = Repositories::GithubTrendingService.search query, limit
  end

  def index
    @repositories = Repository.all
  end

  def show
  end

  private

  def set_languages
    @languages = %w[elixir javascript ruby go python]
  end

  def set_repository
    @repository = Repository.find(params[:id])
  end

  def query
    "language:#{language}"
  end

  def language
    @current_language = params.fetch :language, @languages.first
  end

  def limit
    params.fetch :limit, 10
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Ateliware - Trending</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!--     Fonts and icons     -->
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,300,700' rel='stylesheet' type='text/css'>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
</head>

<body>
    <nav class="navbar navbar-toggleable-md fixed-top navbar-transparent" color-on-scroll="500">
        <div class="container">
            <div class="navbar-translate">
                <button class="navbar-toggler navbar-toggler-right navbar-burger" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar"></span>
                    <span class="navbar-toggler-bar"></span>
                    <span class="navbar-toggler-bar"></span>
                </button>
                <a class="navbar-brand" href="https://www.ateliware.com.br">Ateliware</a>
            </div>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" rel="tooltip" title="Star on GitHub" data-placement="bottom" href="https://www.github.com/mgiacomini/trending" target="_blank">
                            <i class="fa fa-github"></i>
                            <p class="hidden-lg-up">GitHub</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper">
      <%= yield %>
	</div>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <nav class="footer-nav">
                    <ul>
                        <li><a href="http://www.ateliware.com.br">Ateliware</a></li>
                        <li><a href="http://github.com/trending">Trending</a></li>
                    </ul>
                </nav>
                <div class="credits ml-auto">
                    <span class="copyright">
                        © <script>document.write(new Date().getFullYear())</script>, made with <i class="fa fa-heart heart"></i> by Mauricio G. Girardello
                    </span>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>

app/views/repositories/_head.html.erb
<div class="section section-dark">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <h2 class="title">Trending Repositories</h2>
        <p class="description">
          This is a very basic app, and has a unique purpouse, that is find and show trending repositories.
          You can choose between the languages below:
        </p>
        <div>
          <% languages.each do |lang| %>
            <%= link_to lang, search_repositories_path(language: lang), class: 'btn btn-outline-danger btn-round' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/repositories/_list.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <% unless @current_language.nil? %>
          <p>You are seeing trending repositories for: <%= @current_language %></p>
        <% end %>
        <table class="table table-striped table-responsive">
          <thead>
            <tr>
              <th>Language</th>
              <th>Forks count</th>
              <th>Watchers count</th>
              <th>Name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          <% repositories.each do |repository| %>
            <tr>
              <td><%= repository.language %></td>
              <td><%= repository.forks_count %></td>
              <td><%= repository.watchers_count %></td>
              <td><%= repository.name %></td>
              <td><%= link_to 'Show', repository, class: 'btn btn-outline-danger btn-round' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/repositories/index.html.erb
<%= render 'head', languages: @languages %>

<%= render 'list', repositories: @repositories %>

app/views/repositories/search.html.erb
<%= render 'head', languages: @languages %>

<%= render 'list', repositories: @repositories %>

app/views/repositories/show.html.erb
<%= render 'head', languages: @languages %>

<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <h2><%= @repository.name %> / <%= @repository.language %></h2>

        <p>
          <strong>Github ID:</strong>
          <%= @repository.github_id %>
        </p>

        <p>
          <strong>Forks count:</strong>
          <%= @repository.forks_count %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @repository.description %>
        </p>

        <p>
          <strong>Watchers count:</strong>
          <%= @repository.watchers_count %>
        </p>

        <p>
          <strong>Url:</strong>
          <%= @repository.url %>
        </p>

        <%= link_to 'Back', repositories_path %>

      </div>
    </div>
  </div>
</div>